### ISSUE TITLE
HackRF

### ISSUE THREAD

**Issue by LunaEros** [Anjum9694/Anjum9694#1]
I can't find an email for you.  I wanted to email and ask if you finally found a way turn on the Bias-T in the HackRF One and keep it on to use in SDRSharp.  I am wanting to do the exact same thing.
Please let me know if you have.  My email is stormfront96@gmail.com  name is Stephen N0UHF

**Comment by Anjum9694** [comment]
Hello, I didn't have time to decompile SDR# so I went for an external Bias-T injector instead. I heard some HackRF units have terrible antenna port protection so better off not using internal Bias-T anyway.

**Comment by LunaEros** [comment]
Thanks for the update.  I figured I might have to go that route with it. That's why I have a antenna DC block coming in. My external LNA can also be powered by a mini-usb plug. The DC Block will stop the voltage from traveling back into the HackRF through the antenna port.  Hopefully my wideband external LNA works better than the HackRF's built in one.
